### ISSUE TITLE
Recent and upcoming features for Handbook, design standards

### ISSUE THREAD

**Issue by mbland** [18F/guides-style#49]
With all the features going in to support the 18F/handbook design, I thought I'd enumerate them here:

- [X] #43: Breadcrumbs implementation (repeated in #44 thanks to a botched force-push on my part). Already submitted, but I've not yet added an HTML fragment to the `guides_style_18f` templates.
- [x] #45: Flat namespacing, whereby the permalinks corresponding to the directory structure of the `_pages` collection are flattened such that every page is a direct child of `{{ site.baseurl }}`, e.g. `/about-us/offices/new-york-city/` becomes `/new-york-city/`.
- [x] #46: Automatically generated nodes in the `navigation:` list in `_config.yml` for directories, e.g. for `/about-us/` and `/about-us/offices/`, or for `/offices/` in the presence of flat namespacing (#45).
- [x] #47 Generated pages from `navigation:` nodes marked with `generated: true`. The default is to generate a page with a meta redirect to an ID on the home page, e.g. `/offices/` will redirect to `/#offices`.
- [x] 18F/jekyll_pages_api_search#15: Removes dependency on Angular, and generates a search results page rather than a dynamic drop-down.
- [x] #48: Incorporates the revamped search page implementation from 18F/jekyll_pages_api_search#15.
- [x] 18F/handbook#566: Integrates support from #43 (and #44), #45, #46, and #47 into the Handbook.
- [x] 18F/handbook#567: Depends on 18F/handbook#566 and integrates support from #48 into the Handbook.

The screenshots below show the changes in action in both 18F/guides-template and 18F/handbook.

cc: @andrewmaier @mtorres253 @ccostino @ertzeid @catherinedevlin @nicoleslaw 

![handbook-demo](https://cloud.githubusercontent.com/assets/301547/13030803/1dbb3da0-d285-11e5-8189-c6bbfd6f599b.gif)

![guides-search-demo](https://cloud.githubusercontent.com/assets/301547/13036790/489b5e50-d33f-11e5-9ba5-943bc6094650.gif)

**Comment by mbland** [comment]
It is finished. Behold: https://pages-internal.18f.gov/handbook/
